version: '3.4'

services:
  escalade:
    image: ccs/escalade
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3500:3500"
    volumes:
      - ./static/:/app/static/
    restart: always
